services:
  hokai:
    image: ghcr.io/tiagosantini/hokai:0.2.0-alpha.1
    container_name: hokai
    restart: unless-stopped
    volumes:
      - hokai_data:/var/lib/hokai
      - ./docker/appsettings.json:/etc/hokai/appsettings.json:ro
    environment:
      - TZ=America/Sao_Paulo

volumes:
  hokai_data:
